# Configuration file for PetroCast model

dataset= "examples/raw/data1_oil_his_havard.csv"  # Ensure this file exists and follows expected formatting
urr_file= "examples/processed/Oil_estimate_sorted.csv"  # Verify that this file contains a 'value' column for URR extraction
unit= "EJ"  # Unit of measurement, options: "EJ" or "Gb" - Consider validating this input in the main script
